### PR TITLE
Milestone 6

### PR DESCRIPTION
**Pull request by canriquez**
In this milestone, we implement friendships with 2 rows for mutual friendship.
- We create 2 records in the Friendship model to account for the bi-directional friendship as per requirement.
- All unit/integration tests passed.

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi team :wave: 

You have met the project requirements. However, the linter checks are failing.

Please fix it, then submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by canriquez** [comment]
Hi @uche-inyama   our local copy has no offenses. Rubocop is not failing as you can see in this image below:

image

The errors are Robocop related and they only show on the github. We have no responsibility to fix them.

image

Please approve the project.

Regards
Carlos

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Hi @canriquez @HADDADSOHAIB,
- It seems that your linter config files, `.rubocop.yml` file has been modified and the last few lines have been removed, please use the file provided by microverse [here](https://github.com/microverseinc/linters-config/blob/master/ror/.rubocop.yml) (hopefully this fixes the linter error on github!), remember you shouldn't be modifying the linter config files see [screenshot](https://github.com/microverseinc/linters-config/blob/master/ror/.rubocop.yml) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)

**Kindly make the required change then request for another review**
_Feel free to reach out to me on slack (Fatima) if you have any questions or need any help_

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @canriquez and @HADDADSOHAIB  :balloon: :lollipop: 

### You've done a great job with this project, claps to you for adding a badge for pending friendship request :clap: :clap: :clap: :1st_place_medal:  I think your project is good enough to be approved still I strongly recommend you  add a little more to your Readme file so please keep reading

## [OPTIONAL]

#### General

- [ ] Add a product screenshot, don't use the login page.

- [ ] Edit your Setup section, for your project to run in other computers you need to run the bundler but also commands to set up the database and run the server let's add them

- [ ] Add the Usage section describing with examples and screenshots how to accept or decline a friendship 

- [ ] Include an Automated Test section explaining how to run the test cases for example: 
```ruby
rspec spec/integration/
```
### That's it, team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: (or not) and submit project completion form when you are done :memo: 

Any question? please ask on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: APPROVED :green_apple:

**Pull request merged**
